version: '3.8'  # Update to a newer version to support healthcheck conditions
services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://db:3306/world
      - DB_USER=root
      - DB_PASSWORD=example

  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: world
    ports:
      - "33060:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5










