name: A workflow for MyDevOps application
on: push

jobs:
  build:
    name: MyDevOps Analysis Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package with Maven
        run: mvn package
      - name: Build Docker Image
        run: docker build -t mydevopsimage .
      - name: Run image
        run: docker run --name mydevopscontainer -d mydevopsimage
      - name: View logs
        run: docker logs mydevopscontainer
